# general settings
name: UDCUNet-SIT4
model_type: UDCModel
scale: 1
num_gpu: 4
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: udc_pair_train
    type: PairedImgPSFNpyDataset
    lq_map_type: norm
    gt_map_type: norm
    lq_map_range: 1023.
    gt_map_range: 1023.
    filename_tmpl: '{}'
    io_backend:
      type: npy
    folders:
      udc-sit-train:
        dataroot_lq: datasets/training/input
        dataroot_gt: datasets/training/GT

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 20
    prefetch_mode: ~

  val:
    name: udc_val
    type: PairedImgPSFNpyDataset
    lq_map_type: norm
    gt_map_type: norm
    lq_map_range: 1023.
    gt_map_range: 1023.
    io_backend:
      type: npy
    folders:
      udc-sit-validation:
        dataroot_lq: datasets/validation/input
        dataroot_gt: datasets/validation/GT

#### network structures
# do not change
network_g:
  type: UDCUNet
  nf: 32
  in_nc: 4
  out_nc: 4
  depths: [2,2,2,8,2,2,2]
  DyK_size: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000, 100000, 150000, 150000, 150000, 150000, 150000]
    restart_weights: [ 1, 1, 1, 1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: clamp_L1loss

# validation settings
val:
  val_freq: !!float 120000 
  save_img: true 
  dng_info: background.dng # path to background.dng file
  max_pxl: 1023.
  clamp:
    min: 0.
    max: 1.

  metrics:
    psnr: 
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 250 
  save_checkpoint_freq: !!float 120000
  # do not modify or delete below
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
# do not change or delete below
dist_params:
  backend: nccl
  port: 29500
